# Generated by Django 6.0.1 on 2026-01-23 05:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du cabinet')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Cabinet',
                'verbose_name_plural': 'Cabinets',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la spécialité')),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône ou classe CSS", max_length=50)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('telephone_urgence', models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence")),
                ('adresse_complete', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Numéro de sécurité sociale')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('preference_notification', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('les_deux', 'Email et SMS'), ('aucune', 'Aucune')], default='email', max_length=10, verbose_name='Préférence de notification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255, verbose_name='Mot de passe (hashé)')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('numero_rpps', models.CharField(help_text='Répertoire Partagé des Professionnels de Santé', max_length=11, unique=True, verbose_name='Numéro RPPS')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL de la photo')),
                ('tarif_consultation', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif de consultation (€)')),
                ('accepte_teleconsultation', models.BooleanField(default=False, verbose_name='Accepte la téléconsultation')),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=15, verbose_name='Statut de validation')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('valide_par_admin', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionnels_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (Admin)')),
            ],
            options={
                'verbose_name': 'Professionnel',
                'verbose_name_plural': 'Professionnels',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('duree_creneau', models.IntegerField(default=30, help_text="Durée d'un créneau de rendez-vous en minutes", validators=[django.core.validators.MinValueValidator(5)], verbose_name='Durée du créneau (minutes)')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.cabinet')),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='appointments.professionnel')),
            ],
            options={
                'verbose_name': 'Disponibilité horaire',
                'verbose_name_plural': 'Disponibilités horaires',
                'ordering': ['professionnel', 'jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionnelCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('est_principal', models.BooleanField(default=False, verbose_name='Cabinet principal')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.cabinet')),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.professionnel')),
            ],
            options={
                'verbose_name': 'Professionnel - Cabinet',
                'verbose_name_plural': 'Professionnels - Cabinets',
                'unique_together': {('professionnel', 'cabinet')},
            },
        ),
        migrations.AddField(
            model_name='professionnel',
            name='cabinets',
            field=models.ManyToManyField(related_name='professionnels', through='appointments.ProfessionnelCabinet', to='appointments.cabinet', verbose_name='Cabinets'),
        ),
        migrations.AddField(
            model_name='professionnel',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professionnels', to='appointments.specialite', verbose_name='Spécialité'),
        ),
        migrations.CreateModel(
            name='MotifConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('duree_estimee', models.IntegerField(help_text='Durée en minutes', validators=[django.core.validators.MinValueValidator(5)], verbose_name='Durée estimée (minutes)')),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif (€)')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motifs_consultation', to='appointments.specialite', verbose_name='Spécialité')),
            ],
            options={
                'verbose_name': 'Motif de consultation',
                'verbose_name_plural': 'Motifs de consultation',
                'ordering': ['specialite', 'libelle'],
                'unique_together': {('specialite', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='appointments.professionnel', verbose_name='Professionnel')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('patient', 'professionnel')},
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('statut', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('no_show', 'Patient absent')], default='confirme', max_length=10)),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('teleconsultation', 'Téléconsultation')], default='presentiel', max_length=20)),
                ('notes_patient', models.TextField(blank=True, verbose_name='Notes du patient')),
                ('notes_professionnel', models.TextField(blank=True, verbose_name='Notes du professionnel')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('rappel_envoye', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='appointments.cabinet', verbose_name='Cabinet')),
                ('motif_consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='appointments.motifconsultation', verbose_name='Motif de consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='appointments.professionnel', verbose_name='Professionnel')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date', '-heure_debut'],
                'indexes': [models.Index(fields=['date', 'professionnel'], name='appointment_date_7c8184_idx'), models.Index(fields=['patient', 'date'], name='appointment_patient_a9439f_idx')],
            },
        ),
    ]
