# Generated by Django 4.2.7 on 2026-01-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_compte',
            field=models.CharField(choices=[('client', 'Client'), ('professionnel', 'Professionnel')], default='client', max_length=15, verbose_name='Type de compte'),
        ),
    ]
