# Generated by Django 4.2.7 on 2026-01-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_user_type_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Est administrateur'),
        ),
    ]
