# Generated by Django 4.2.7 on 2026-01-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionnel',
            name='numero_rpps',
            field=models.CharField(blank=True, help_text='Répertoire Partagé des Professionnels de Santé', max_length=11, null=True, unique=True, verbose_name='Numéro RPPS'),
        ),
    ]
