# Generated by Django 4.2.7 on 2026-01-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_professionnel_numero_rpps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionnel',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mot de passe (hashé)'),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
    ]
